[Icon Theme]
Name=dde25-dark
Comment=DDE V25 (bloom, deepin-icon-theme 2024.07.31) status icons for gxde-top-panel, dark panel
Inherits=gxde-dark,gxde
Directories=status/20,status/16,places/16

[status/20]
Size=20
Context=Status
Type=Scalable
MinSize=8
MaxSize=64

[status/16]
Size=16
Context=Status
Type=Scalable
MinSize=8
MaxSize=64

[places/16]
Size=16
Context=Places
Type=Scalable
MinSize=8
MaxSize=64
